version: "3.8"

services:
  # =========================================================
  # MLflow Tracking Server
  # =========================================================
    mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
      - ./models:/models
    environment:
      - GUNICORN_CMD_ARGS=--forwarded-allow-ips="*" --proxy-allow-from="*" --allow-hosts="*"
    command: >
      mlflow ui
      --backend-store-uri file:///mlruns
      --default-artifact-root file:///mlruns
      --host 0.0.0.0
      --port 5000
      --gunicorn-opts "--forwarded-allow-ips='*' --proxy-allow-from='*' --allow-hosts='*'"
    restart: always
  # =========================================================
  # ARF IDS API (FastAPI)
  # =========================================================
  arf-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arf-api
    depends_on:
      - mlflow
    ports:
      - "80:8000"
    volumes:
      - ./models:/app/models
      - ./dataset:/app/dataset
      - ./mlruns:/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    restart: always

  # =========================================================
  # Prometheus Monitoring
  # =========================================================
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: always

  # =========================================================
  # Grafana Initialization (auto fix permission if bind mount)
  # =========================================================
  grafana-init:
    image: busybox
    command: chown -R 472:472 /var/lib/grafana
    volumes:
      - ./grafana_data:/var/lib/grafana

  # =========================================================
  # Grafana Visualization
  # =========================================================
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - grafana-init
    volumes:
      - ./grafana_data:/var/lib/grafana
    user: "472"
    environment:
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
    restart: always

# =========================================================
# Docker-managed Volumes (persistent, no permission issues)
# =========================================================
volumes:
  grafana_data:
  prometheus_data:
