name: Build & Deploy IDS API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ============================
      # 1️⃣ Checkout repo
      # ============================
      - name: Checkout repository
        uses: actions/checkout@v4

      # ============================
      # 2️⃣ Setup Docker build environment
      # ============================
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ============================
      # 3️⃣ Login to DockerHub
      # ============================
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ============================
      # 4️⃣ Build & push image to DockerHub
      # ============================
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/arf-ids-mlops:latest

      # ============================
      # 5️⃣ Trigger Render Deploy Hook
      # ============================
      - name: Trigger Render Deploy Hook
        if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}
        run: |
          echo "🚀 Triggering Render deploy..."
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
          echo "✅ Deploy triggered successfully on Render."
